package(default_visibility = ["//visibility:public"])

java_library(
  name = "month",
  srcs = glob(["*.java"]),
  deps = [
    "@maven//:com_fasterxml_jackson_core_jackson_annotations",
    "@maven//:javax_annotation_javax_annotation_api",
  ],
)