java_binary(
    name = "runner",
    srcs = ["Runner.java"],
    main_class = "com.ynabmonthlyreport.Runner",
    data = ["//src/main/resources"],
    deps = [
        "//src/main/java/com/ynabmonthlyreport/email",
        "//src/main/java/com/ynabmonthlyreport/model",
        "//src/main/java/com/ynabmonthlyreport/model/config",
        "//src/main/java/com/ynabmonthlyreport/model/month",
        "//src/main/java/com/ynabmonthlyreport/report",
        "//src/main/java/com/ynabmonthlyreport/scheduler",
        "//src/main/java/com/ynabmonthlyreport/ynab",
    ],
)
